// Generated by gencpp from file astra_camera/GetCameraParams.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_GETCAMERAPARAMS_H
#define ASTRA_CAMERA_MESSAGE_GETCAMERAPARAMS_H

#include <ros/service_traits.h>


#include <astra_camera/GetCameraParamsRequest.h>
#include <astra_camera/GetCameraParamsResponse.h>


namespace astra_camera
{

struct GetCameraParams
{

typedef GetCameraParamsRequest Request;
typedef GetCameraParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraParams
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::GetCameraParams > {
  static const char* value()
  {
    return "82a0d82977d6826869eb4772054042e0";
  }

  static const char* value(const ::astra_camera::GetCameraParams&) { return value(); }
};

template<>
struct DataType< ::astra_camera::GetCameraParams > {
  static const char* value()
  {
    return "astra_camera/GetCameraParams";
  }

  static const char* value(const ::astra_camera::GetCameraParams&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::GetCameraParamsRequest> should match
// service_traits::MD5Sum< ::astra_camera::GetCameraParams >
template<>
struct MD5Sum< ::astra_camera::GetCameraParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetCameraParams >::value();
  }
  static const char* value(const ::astra_camera::GetCameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetCameraParamsRequest> should match
// service_traits::DataType< ::astra_camera::GetCameraParams >
template<>
struct DataType< ::astra_camera::GetCameraParamsRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetCameraParams >::value();
  }
  static const char* value(const ::astra_camera::GetCameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::GetCameraParamsResponse> should match
// service_traits::MD5Sum< ::astra_camera::GetCameraParams >
template<>
struct MD5Sum< ::astra_camera::GetCameraParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetCameraParams >::value();
  }
  static const char* value(const ::astra_camera::GetCameraParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetCameraParamsResponse> should match
// service_traits::DataType< ::astra_camera::GetCameraParams >
template<>
struct DataType< ::astra_camera::GetCameraParamsResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetCameraParams >::value();
  }
  static const char* value(const ::astra_camera::GetCameraParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_GETCAMERAPARAMS_H
