// Generated by gencpp from file astra_camera/SetString.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_SETSTRING_H
#define ASTRA_CAMERA_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <astra_camera/SetStringRequest.h>
#include <astra_camera/SetStringResponse.h>


namespace astra_camera
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::astra_camera::SetString&) { return value(); }
};

template<>
struct DataType< ::astra_camera::SetString > {
  static const char* value()
  {
    return "astra_camera/SetString";
  }

  static const char* value(const ::astra_camera::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::SetStringRequest> should match
// service_traits::MD5Sum< ::astra_camera::SetString >
template<>
struct MD5Sum< ::astra_camera::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetString >::value();
  }
  static const char* value(const ::astra_camera::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetStringRequest> should match
// service_traits::DataType< ::astra_camera::SetString >
template<>
struct DataType< ::astra_camera::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetString >::value();
  }
  static const char* value(const ::astra_camera::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::SetStringResponse> should match
// service_traits::MD5Sum< ::astra_camera::SetString >
template<>
struct MD5Sum< ::astra_camera::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetString >::value();
  }
  static const char* value(const ::astra_camera::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetStringResponse> should match
// service_traits::DataType< ::astra_camera::SetString >
template<>
struct DataType< ::astra_camera::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetString >::value();
  }
  static const char* value(const ::astra_camera::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_SETSTRING_H
