global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 
  publish_frequency: 5.0 
  static_map: true #是否使用一个地图或者地图服务器来初始化代价地图，如果不使用静态地图，这个为false
  rolling_window: true
  width: 20.0
  height: 20.0
  # transform_tolerance: 1
  # cost_scaling_factor: 10.0
  # inflation_radius: 0.1
  # plugins:
  # - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  # - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  # - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
