local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05 
  transform_tolerance: 0.5
  map_type: costmap
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::VoxelLayer'}
    - {name: static_layer,   type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

  inflation_layer:
    inflation_radius: 0.03

  # sonar_layer:
  #   topics: ["/sonar"]
  #   no_readings_timeout: 1.0
  #   clear_threshold : 0.1 
  #   mark_threshold : 0.8
#   clear_on_max_reading : true 

  # cost_scaling_factor: 5
  # inflation_radius: 0.1
