base_global_planner: "global_planner/GlobalPlanner"

base_local_planner: "dwa_local_planner/DWAPlannerROS"


shutdown_costmaps: false

controller_frequency: 3.0
controller_patience: 3.0

planner_frequency: 0.5
planner_patience: 3.0

oscillation_timeout: 5.0 #10.0
oscillation_distance: 0.2

conservative_reset_dist: 0.1

escape_vel: 0.0 # -0.5

cost_factor: 1.0
neutral_cost: 55
lethal_cost: 253

GlobalPlanner:
  old_navfn_behavior: false
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false
  allow_unknown: false
  lethal_cost: 253                              
  neutral_cost: 66                              
  cost_factor: 0.55 


