# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myagv_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_ros = QtWidgets.QPushButton(self.centralwidget)
        self.open_ros.setGeometry(QtCore.QRect(10, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open_ros.setFont(font)
        self.open_ros.setStyleSheet("QPushButton:pressed{\n"
                                    "   background-color:#c7c7d0;\n"
                                    "}\n"
                                    "")
        self.open_ros.setObjectName("open_ros")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 55, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 50, 211, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.teleop_button = QtWidgets.QPushButton(self.centralwidget)
        self.teleop_button.setGeometry(QtCore.QRect(30, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.teleop_button.setFont(font)
        self.teleop_button.setStyleSheet("QPushButton:pressed{\n"
                                         "   background-color:#c7c7d0;\n"
                                         "}\n"
                                         "")
        self.teleop_button.setObjectName("teleop_button")
        self.mapping_button = QtWidgets.QPushButton(self.centralwidget)
        self.mapping_button.setGeometry(QtCore.QRect(290, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mapping_button.setFont(font)
        self.mapping_button.setStyleSheet("QPushButton:pressed{\n"
                                          "   background-color:#c7c7d0;\n"
                                          "}\n"
                                          "")
        self.mapping_button.setObjectName("mapping_button")
        self.save_mapping = QtWidgets.QPushButton(self.centralwidget)
        self.save_mapping.setGeometry(QtCore.QRect(420, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_mapping.setFont(font)
        self.save_mapping.setStyleSheet("QPushButton:pressed{\n"
                                        "   background-color:#c7c7d0;\n"
                                        "}\n"
                                        "")
        self.save_mapping.setObjectName("save_mapping")
        self.navigation_button = QtWidgets.QPushButton(self.centralwidget)
        self.navigation_button.setGeometry(QtCore.QRect(660, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.navigation_button.setFont(font)
        self.navigation_button.setStyleSheet("QPushButton:pressed{\n"
                                             "   background-color:#c7c7d0;\n"
                                             "}\n"
                                             "")
        self.navigation_button.setObjectName("navigation_button")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 250, 741, 281))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.handle_control = QtWidgets.QPushButton(self.centralwidget)
        self.handle_control.setGeometry(QtCore.QRect(160, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.handle_control.setFont(font)
        self.handle_control.setStyleSheet("QPushButton:pressed{\n"
                                          "   background-color:#c7c7d0;\n"
                                          "}\n"
                                          "")
        self.handle_control.setObjectName("handle_control")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(480, 50, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("QPushButton:pressed{\n"
                                        "   background-color:#c7c7d0;\n"
                                        "}\n"
                                        "")
        self.close_button.setObjectName("close_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setTabletTracking(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(670, 50, 41, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(720, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setTabletTracking(True)
        self.label_5.setObjectName("label_5")
        self.modify_file = QtWidgets.QPushButton(self.centralwidget)
        self.modify_file.setGeometry(QtCore.QRect(540, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.modify_file.setFont(font)
        self.modify_file.setStyleSheet("QPushButton:pressed{\n"
                                       "   background-color:#c7c7d0;\n"
                                       "}\n"
                                       "")
        self.modify_file.setObjectName("modify_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_ros.setText(_translate("MainWindow", "Open slam"))
        self.label.setText(_translate("MainWindow", "选择程序："))
        self.comboBox.setItemText(0, _translate("MainWindow", "键盘控制"))
        self.comboBox.setItemText(1, _translate("MainWindow", "手柄控制"))
        self.comboBox.setItemText(2, _translate("MainWindow", "实时建图"))
        self.comboBox.setItemText(3, _translate("MainWindow", "保存建图"))
        self.comboBox.setItemText(4, _translate("MainWindow", "实时导航"))
        self.teleop_button.setText(_translate("MainWindow", "键盘控制"))
        self.mapping_button.setText(_translate("MainWindow", "实时建图"))
        self.save_mapping.setText(_translate("MainWindow", "保存建图"))
        self.navigation_button.setText(_translate("MainWindow", "实时导航"))
        self.label_2.setText(_translate("MainWindow", "日志："))
        self.handle_control.setText(_translate("MainWindow", "手柄控制"))
        self.label_3.setText(_translate("MainWindow", "关闭键盘控制："))
        self.close_button.setText(_translate("MainWindow", "close teleop"))
        self.label_4.setText(_translate("MainWindow", "默认速度："))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "m/s"))
        self.modify_file.setText(_translate("MainWindow", "修改launch文件"))
